version: '3'

services:
  bpmn:
    image: francizampi/reproducibility-behavioural:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PAIRS_CATALOG_CSV=assets/pairs-catalog-models.csv
    volumes:
      - ./output/:/app/results